factors out the updating doc into separate pages
bottlerocket-os/project-website pull request #50
Opened 2023-03-07 22:10 UTC by mchaker

**Issue number:**

Closes #48 

**Description of changes:**

Refactors the Updating Bottlerocket concept document into three separate instructional documents:

- In-Place Updates
- Locking to a Specific Release
- Node Replacement

and cleans up the remaining content in the Updating Bottlerocket concept document.

**Terms of contribution:**

By submitting this pull request, I confirm that my contribution is made under
the terms of the licenses outlined in the LICENSE-SUMMARY file.

2023-03-08 15:01 UTC, stockholmux requested changes
A few small changes - write a couple of intro sentences, move one bundle up a level, and explore a weird rendering issue.

2023-03-08 15:07 UTC, mchaker commented on content/en/os/1.13.x/update/methods/locking-to-a-specific-release/index.markdown
> +title = "Locking to a Specific Release"
I think you're right! I'll make that change.

2023-03-08 21:21 UTC, mchaker commented on content/en/os/1.13.x/concepts/updating-bottlerocket/index.markdown
> +## Conclusion
Hmm... took a look at it, nothing seems to stand out compared to the other markdown files. Permissions are the same and filetype via `file` is the same.

2023-03-09 14:19 UTC, stockholmux commented on content/en/os/1.13.x/concepts/updating-bottlerocket/index.markdown
> +## Conclusion
Actually, it looks like it's rendering correctly now 🤷‍♂️

2023-03-09 14:20 UTC, stockholmux approved these changes
LGTM

2023-03-09 16:00 UTC, merged